### ISSUE TITLE
Extensions for other browsers

### ISSUE THREAD

**Issue by shreyasminocha** [plibither8/asciinema-player-for-github#1]
Would it be possible to build a firefox add-on from this code?

**Comment by plibither8** [comment]
Welp, porting the extension to FF would have been super simple had Chrome's APIs (the [CSP modifications](https://github.com/plibither8/asciinema-player-for-github#content-security-policy-modification) in [src/background.js](https://github.com/plibither8/asciinema-player-for-github/blob/master/src/background.js)) not been a part of the code. I don't know much about Firefox development/APIs.

It'd be great if you could contribute if you a thing or two about FF add-ons. :smile: 

Thanks!

**Comment by shreyasminocha** [comment]
Looks like FF ≥45 supports [`onHeadersReceived`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#webRequest). Moreover, [FF supports the `chrome` namespace as well (although it's not part of the spec)](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#Firefox_supports_both_the_chrome_and_browser_namespaces).

**Comment by shreyasminocha** [comment]
Let me try to file a PR :)

**Comment by plibither8** [comment]
> Moreover, [FF supports the `chrome` namespace as well (although it's not part of the spec)](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Chrome_incompatibilities#Firefox_supports_both_the_chrome_and_browser_namespaces).

Interesting. That's pretty generous of Firefox.

> Let me try to file a PR :)

Great :+1:

**Comment by shreyasminocha** [comment]
I've tested that it's working, but I think it's best if you [package](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Getting_started_with_web-ext#Packaging_your_extension) and [submit](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution/Submitting_an_add-on) because it involves signing and other stuff that would best be done using your keys/accounts.

**Comment by shreyasminocha** [comment]
Porting to [Edge](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions) ([supports `webRequest.onHeadersReceived`](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/supported-apis#webrequest)) and Opera (also supports [supports `webRequest.onHeadersReceived`](https://dev.opera.com/extensions/apis/)).

**Comment by plibither8** [comment]
That's great, I'll look into those browsers too, thanks!

Meanwhile, testing the add-on on FF on my machine, I'm getting the following error:
![image](https://user-images.githubusercontent.com/31861755/52550077-923d2500-2dfc-11e9-92b0-4f8e18c772a6.png)

How should I proceed?

**Comment by shreyasminocha** [comment]
Strange, I cannot reproduce. I'm running Firefox Quantum 64.0 (64-bit). Which version are you running?

**Comment by plibither8** [comment]
Firefox Quantum 65.0 (64-bit) on Linux. Just so we are on the same page, I am testing the add-on on `about:debugging`, yeah?

**Comment by plibither8** [comment]
I was too quick to call it off: the add-on is working alright, regardless of that error :sweat_smile:.

I'll package and submit the add-on for FF tonight.

Cheers!

**Comment by shreyasminocha** [comment]
I was testing via `web-ext`, but great that it worked. Cheers!

**Comment by plibither8** [comment]
Hey @shreyasminocha! This has come way too late, but finally: https://addons.mozilla.org/en-US/firefox/addon/asciinema-player-for-github/

Apologies for the delay :sweat_smile:

**Comment by shreyasminocha** [comment]
Hey, that's great. Thanks!
